name: CD - Blue-Green Deploy

on:
  # Manual trigger so you stay in control
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update system packages (GitHub runner)
        run: sudo apt-get update -y

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

            - name: Get ALB listener info
        run: |
          aws elbv2 describe-listeners \
            --listener-arns ${{ secrets.ALB_LISTENER_ARN }} \
            --query "Listeners[0].DefaultActions[0].TargetGroupArn" \
            --output text > current_tg.txt

      - name: Determine active environment
        id: determine_env
        run: |
          CURRENT_TG=$(cat current_tg.txt)

          if [ "$CURRENT_TG" = "${{ secrets.BLUE_TG_ARN }}" ]; then
            echo "active=blue" >> $GITHUB_OUTPUT
            echo "inactive=green" >> $GITHUB_OUTPUT
          else
            echo "active=green" >> $GITHUB_OUTPUT
            echo "inactive=blue" >> $GITHUB_OUTPUT
          fi

      - name: Show determined environments
        run: |
          echo "Active environment: ${{ steps.determine_env.outputs.active }}"
          echo "Inactive environment: ${{ steps.determine_env.outputs.inactive }}"
